# Site settings
title: arussellsaw.github.io
email: 
description: > # tech and twattery
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://arussellsaw.github.io" # the base hostname & protocol for your site
twitter_username: alexrussellsaw
github_username:  arussellsaw

# Build settings
markdown: kramdown
